### ISSUE TITLE
Release app on F-droid

### ISSUE THREAD

**Issue by cygnet3** [cygnet3/danawallet#38]
Once we have the first version ready, we should try to get the app on F-droid.

**Comment by Giszmo** [comment]
Is the app or are there any plans to release it on Google Play?

**Comment by cygnet3** [comment]
Yes, google play store and the apple app store are planned as well, but F-droid should be slightly less friction so that one is targeted first.

**Comment by yashrajd** [comment]
Given fdroid release is done, time to close ticket?

**Comment by cygnet3** [comment]
Yep, probably a good idea. We have a personal F-droid repository for Dana: https://fdroid.silentpayments.dev/

Dana isn't available in the official F-droid repository yet, but we should probably make a separate issue for that.

**Comment by cygnet3** [comment]
I added a section to the README for downloading the app using F-Droid.
