### ISSUE TITLE
Spending while not having sync to the last block

### ISSUE THREAD

**Issue by Sosthene00** [cygnet3/danawallet#93]
I just realized that nothing prevents us from spending without scanning. While it's unlikely this would result in accidental double spends, it could mean that the balance we display as available is less than in reality.

Maybe blocking is not the right strategy, but at the very least we should display a warning that says something like "Your wallet is not up to date, displayed balance might be less than what you actually have"

**Comment by cygnet3** [comment]
Yes good point. I think this is one of those things that we should discuss during a design call.

**Comment by cygnet3** [comment]
Fixed in https://github.com/cygnet3/danawallet/pull/94
